name: Multi project

on: push

jobs:
  build_jobs:
     runs-on: ubuntu-latest
     steps:
     - name: Hello world
       run: echo "Hello world"

     - name: Execute Cowsay CMD
       run: cowsay -f dragon "Run for cover , I am a Dragon...RAWR" >> dragon.txt	 

  test_jobs:
     runs-on: ubuntu-latest
     steps:
     - name: Test File Exists
       run: grep -i "dragon" dragon.txt
     - name: Sleep for 10 seconds
       run: sleep 10	   
	   

  deploy_jobs:
     runs-on: ubuntu-latest
     steps:
     - name: deploy world
       run: echo "deploy world" 
     - name: Read File
       run: cat dragon.txt