name: "Multi project"

on: push

jobs:
  build_jobs:
     runs-on: ubuntu-latest
     steps:
     - name: Hello world
       run: echo "Hello world"

     - name: Execute Cowsay CMD
       run: cowsay -f dragon "Run for cover , I am a Dragon...RAWR"	

  test_jobs:
     runs-on: ubuntu-latest
     steps:
     - name: test world
       run: echo "test world" 

  deploy_jobs:
     runs-on: ubuntu-latest
     steps:
     - name: deploy world
       run: echo "deploy world"  