name: "Multi project"

on: push

jobs:
  build_jobs:
     runs-on: ubuntu-latest
     steps:
     - name: Hello world
       run: echo "Hello world"

     - name: Install cowsay
       run: sudo apt-get install cowsay -y

     - name: Execute Cowsay CMD
       run: cowsay -f dragon "Run for cover , I am a Dragon...RAWR"	>> dragon.txt

     - name: Upload Dragon text file
       uses: actions/upload-artifact@v3
       with:
         name: dragon-text-file
         path: dragon.txt

  test_jobs:
     needs: build_jobs
     runs-on: ubuntu-latest
     steps:
     - name: test world
       run: echo "test world" 

     - name: Download Dragon text file
       uses: actions/download-artifact@v3
       with:
        name: dragon-text-file

     - name: Test File Exists
       run: grep -i "dragon" dragon.txt

  deploy_jobs:
     needs: [build_jobs,test_jobs]
     runs-on: ubuntu-latest
     steps:
     - name: deploy world
       run: echo "deploy world" 
       
     

     - name: Download Dragon text file
       uses: actions/download-artifact@v3
       with:
        name: dragon-text-file

     - name: Read File
       run: cat dragon.txt