name: "Multi project"

on: push

jobs:
  build_jobs:
     runs-on: ubuntu-latest
     steps:
     - name: Hello world
       run: echo "Hello world"

     - name: Install cowsay
       run: sudo apt-get install cowsay -y

     - name: Execute Cowsay CMD
       run: cowsay -f dragon "Run for cover , I am a Dragon...RAWR"	>> dragon.txt

  test_jobs:
     runs-on: ubuntu-latest
     steps:
     - name: test world
       run: echo "test world" 

     - name: Test File Exists
       run: grep -i "dragon" dragon.txt

  deploy_jobs:
     runs-on: ubuntu-latest
     steps:
     - name: deploy world
       run: echo "deploy world" 
       
     - name: Read File
       run: cat dragon.txt